set(CMAKE_SYSTEM_NAME Generic)
list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES AUTH_MCPU AUTH_FPU ARM_TOOLCHAIN_PREFIX)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(ARM_TOOLCHAIN_PREFIX "arm-none-eabi" CACHE STRING "Arm toolchain path/prefix")
set(CMAKE_C_COMPILER "${ARM_TOOLCHAIN_PREFIX}-gcc")
set(CMAKE_ASM_COMPILER "${ARM_TOOLCHAIN_PREFIX}-gcc")
set(CMAKE_OBJCOPY "${ARM_TOOLCHAIN_PREFIX}-objcopy")
set(CMAKE_SIZE "${ARM_TOOLCHAIN_PREFIX}-size")
if(NOT AUTH_MCPU OR NOT AUTH_FPU)
    message(FATAL_ERROR "Select a configured STM32 INSTANCE before loading the toolchain")
endif()
set(CPU_FLAGS "-mcpu=${AUTH_MCPU} -mfpu=${AUTH_FPU} -mfloat-abi=hard -mthumb")
set(CMAKE_C_FLAGS_INIT "${CPU_FLAGS} -ffunction-sections -fdata-sections")
set(CMAKE_ASM_FLAGS_INIT "${CPU_FLAGS} -x assembler-with-cpp")
set(CMAKE_EXE_LINKER_FLAGS_INIT "${CPU_FLAGS} -nostartfiles --specs=nano.specs --specs=nosys.specs -Wl,--gc-sections")
