set(INSTANCE "posix" CACHE STRING "Instance directory name")
set_property(CACHE INSTANCE PROPERTY STRINGS posix stm32h743vit6 stm32g431cbu6)
if(DEFINED AUTH_BOARD)
    message(FATAL_ERROR "AUTH_BOARD was replaced by INSTANCE; use a fresh build directory")
endif()
if(DEFINED SIMPLE_CONFIGURED_INSTANCE AND NOT SIMPLE_CONFIGURED_INSTANCE STREQUAL INSTANCE)
    message(FATAL_ERROR "Use a separate build directory for each INSTANCE")
endif()
set(SIMPLE_CONFIGURED_INSTANCE "${INSTANCE}" CACHE INTERNAL "Configured instance")
if(NOT INSTANCE STREQUAL "posix")
    if(NOT INSTANCE MATCHES "^stm32(h7|g4)[a-z0-9]+$")
        message(FATAL_ERROR "Unknown INSTANCE: ${INSTANCE}")
    endif()
    set(instance_file "${CMAKE_CURRENT_LIST_DIR}/../instances/stm32/stm32${CMAKE_MATCH_1}xx/${INSTANCE}/CMakeLists.txt")
    if(NOT EXISTS "${instance_file}")
        message(FATAL_ERROR "Missing instance configuration: ${instance_file}")
    endif()
    include("${instance_file}")
    if(NOT DEFINED CMAKE_TOOLCHAIN_FILE)
        set(CMAKE_TOOLCHAIN_FILE "${CMAKE_CURRENT_LIST_DIR}/arm-none-eabi.cmake" CACHE FILEPATH "Toolchain")
    endif()
endif()
